export const usersProfileActionTypes = {
  USER_PROFILE_INIT_ACTION: 'USER_PROFILE_INIT_ACTION',
  USER_PROFILE_SUCCESS_ACTION: 'USER_PROFILE_SUCCESS_ACTION',
  USER_PROFILE_FAIL_ACTION: 'USER_PROFILE_FAIL_ACTION',

  USER_UPDATE_INIT_ACTION: 'USER_UPDATE_INIT_ACTION',
  USER_UPDATE_SUCCESS_ACTION: 'USER_UPDATE_SUCCESS_ACTION',
  USER_UPDATE_FAIL_ACTION: 'USER_UPDATE_FAIL_ACTION',
};
