export const loginActionTypes = {
  LOGIN_INIT_ACTION: 'LOGIN_INIT_ACTION',
  LOGIN_SUCCESS_ACTION: 'LOGIN_SUCCESS_ACTION',
  LOGIN_FAIL_ACTION: 'LOGIN_FAIL_ACTION',
};

export const logoutActionTypes = {
  LOGOUT_INIT_ACTION: 'LOGOUT_INIT_ACTION',
  LOGOUT_SUCCESS_ACTION: 'LOGOUT_SUCCESS_ACTION',
  LOGOUT_FAIL_ACTION: 'LOGOUT_FAIL_ACTION',
};

export const registrationActionTypes = {
  REGISTRATION_INIT_ACTION: 'REGISTRATION_INIT_ACTION',
  REGISTRATION_SUCCESS_ACTION: 'REGISTRATION_SUCCESS_ACTION',
  REGISTRATION_FAIL_ACTION: 'REGISTRATION_FAIL_ACTION',
};