export const tradeOptionsTypes = {
  TRADE_OPTIONS_INIT_ACTION : "TRADE_OPTIONS_INIT_ACTION",
  TRADE_OPTIONS_SUCCESS_ACTION : "TRADE_OPTIONS_SUCCESS_ACTION",
  TRADE_OPTIONS_FAIL_ACTION : "TRADE_OPTIONS_FAIL_ACTION",
};