export const deliveryOptionsTypes = {
  DELIVERY_OPTIONS_INIT_ACTION : "DELIVERY_OPTIONS_INIT_ACTION",
  DELIVERY_OPTIONS_SUCCESS_ACTION : "DELIVERY_OPTIONS_SUCCESS_ACTION",
  DELIVERY_OPTIONS_FAIL_ACTION : "DELIVERY_OPTIONS_FAIL_ACTION",
};