export const basketActionTypes = {
  ADD_BASKET_ITEM_ACTION: 'ADD_BASKET_ITEM_ACTION',

  REMOVE_BASKET_ITEM_ACTION: 'REMOVE_BASKET_ITEM_ACTION',

  CHANGE_BASKET_ITEM_ACTION: 'CHANGE_BASKET_ITEM_ACTION',

  REMOVE_ALL_BASKET_ITEMS_ACTION: 'REMOVE_ALL_BASKET_ITEMS_ACTION'
};
