export const sharesActionTypes = {
  ADD_TO_SHARES_ITEM_ACTION: 'ADD_TO_SHARES_ITEM_ACTION',
  INIT_TO_SHARES_ITEM_ACTION: 'INIT_TO_SHARES_ITEM_ACTION',
  FAIL_TO_SHARES_ITEM_ACTION: 'FAIL_TO_SHARES_ITEM_ACTION',
};

export const newsActionTypes = {
  ADD_TO_NEWS_ITEM_ACTION: 'ADD_TO_NEWS_ITEM_ACTION',
  INIT_TO_NEWS_ITEM_ACTION: 'INIT_TO_NEWS_ITEM_ACTION',
  FAIL_TO_NEWS_ITEM_ACTION: 'FAIL_TO_NEWS_ITEM_ACTION',
};
