export const repeatOrderTypes = {
  REPEAT_ORDER_INIT_ACTION : "REPEAT_ORDER_INIT_ACTION",
  REPEAT_ORDER_SUCCESS_ACTION : "REPEAT_ORDER_SUCCESS_ACTION",
  REPEAT_ORDER_FAIL_ACTION : "REPEAT_ORDER_FAIL_ACTION",
};
